# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w1QMEV_cLniM8waiyoQeZVuzex2HUstP
"""

!pip install pandas matplotlib seaborn

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import re
import string
import nltk
from nltk.corpus import stopwords

df = pd.read_csv("/content/500veri.csv")

print("Tekrarlayan satır sayısı", df.duplicated().sum())

# veriyle ilgili temel incelemeler

print("🔹 Veri Boyutu:", df.shape)
print("\n🔹 İlk 5 Satır:")
print(df.head()) #direkt df.head(5) de olur genel yapıyı görmek/kontrol etmek için

print("\n🔹 Veri Hakkında Bilgi:")
print(df.info())

print("\n🔹 Eksik Değerler:")
print(df.isnull().sum())

print("\n🔹 Temel İstatistikler:")
print(df.describe()) #sayısal sutunlar icin
df.describe(include='object') #kategorik sutunlar icin

for col in df.columns:
    print(f"{col}: {df[col].nunique()} benzersiz değer")

numeric_cols = [col for col in df.columns if df[col].dtype == 'int']
for col in numeric_cols:
    print(f"\n{col} dağılımı:")
    print(df[col].value_counts().head(10))



df.hist(figsize=(3,2), bins=10)
plt.show()

# Numerik kolonlar

skewness = df[numeric_cols].skew()
kurtosis = df[numeric_cols].kurtosis()

#sonuclar
skew_kurt_df = pd.DataFrame({'Skewness': skewness, 'Kurtosis': kurtosis})
print("📊 Skewness ve Kurtosis:")
print(skew_kurt_df)

#skewness çarpıklık 0a yakın normal, pozitif sağ çarpık, negatif sol çarpık
#kurtosis basıklık 0 normale yakın, >0 sivri, <0 basık dağılım

for col in numeric_cols:
    plt.figure(figsize=(3,2))
    sns.histplot(df[col], kde=True, color="pink", bins=10)  # kernel density estimate
    plt.title(f"{col} - Histogram & KDE")
    plt.xlabel(col)
    plt.ylabel("Frekans")
    plt.show()

nltk.download('stopwords')

turkish_stopwords = set(stopwords.words('turkish'))

def clean_text(text):
    if pd.isnull(text):
        return ""
    text = text.lower()

    text = re.sub(r'[^\w\sçğıöşü]', ' ', text) #özel karakterleri kaldır
    text = re.sub(r'\d+', '', text)
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = ' '.join([word for word in text.split() if word not in turkish_stopwords])
    text = re.sub(r'\s+', ' ', text).strip()

    return text
df = pd.read_csv("/content/500veri.csv")
df["Temiz_Yorum"] = df["Yorum"].apply(clean_text)

df.to_csv("veriler_temiz.csv", index=False)

print("✅ Temizlenmiş yorumlar 'veriler_temiz.csv' dosyasına kaydedildi!")

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

df = pd.read_csv("/content/veriler_temiz.csv")

print(df.head())
print(df.columns)

df = pd.read_csv("/content/veriler_temiz.csv")

df = df[['Temiz_Yorum', 'Duygu']]
X = df['Temiz_Yorum']
y = df['Duygu']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

vectorizer = TfidfVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)


model = LogisticRegression(max_iter=1000)
model.fit(X_train_vec, y_train)


y_pred = model.predict(X_test_vec)

print("Sınıflandırma Raporu:\n")
print(classification_report(y_test, y_pred, target_names=["Negatif", "Notr", "Pozitif"]))

print("Karmaşıklık Matrisi:\n")
cm=confusion_matrix(y_test, y_pred)
print(cm)

labels = ["Negatif", "Notr", "Pozitif"]

plt.figure(figsize=(4,3))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=labels, yticklabels=labels)
plt.xlabel("Tahmin Edilen Sınıf")
plt.ylabel("Gerçek Sınıf")
plt.show()

df = pd.read_csv("/content/veriler_temiz.csv")

df = df[['Yorum', 'Duygu']] # buraya temiz yorum sutunu gelecek


X_train, X_test, y_train, y_test = train_test_split(
    df['Yorum'], df['Duygu'], test_size=0.2, random_state=42
)


vectorizer = TfidfVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)


model = LogisticRegression(max_iter=1000)
model.fit(X_train_vec, y_train)


y_pred = model.predict(X_test_vec)


print("Sınıflandırma Raporu:\n")
print(classification_report(y_test, y_pred, target_names=["Negatif", "Notr", "Pozitif"]))

print("Karmaşıklık Matrisi:\n")
cm=confusion_matrix(y_test, y_pred)
print(cm)

labels = ["Negatif", "Notr", "Pozitif"]

plt.figure(figsize=(4,3))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=labels, yticklabels=labels)
plt.xlabel("Tahmin Edilen Sınıf")
plt.ylabel("Gerçek Sınıf")
plt.show()

#NÖTR İÇİN AUGMENTATION DENEDİM
!pip install nlpaug transformers sentencepiece pandas
import pandas as pd
import nlpaug.augmenter.word as naw


df = pd.read_csv("/content/veriler_temiz.csv")


neutral_df = df[df['Duygu'] == 2]
neutral_texts = neutral_df['Yorum'].tolist()

aug = naw.ContextualWordEmbsAug(
    model_path='bert-base-multilingual-cased',
    action="substitute"
)


augmented_texts = []
for text in neutral_texts:
    augmented = aug.augment(text, n=3)
    augmented_texts.extend(augmented)

# augmented veriyidf olarak hazırla
aug_df = pd.DataFrame({
    "Duygu": [2]*len(augmented_texts),
    "Yorum Yapan": ["Augmented"]*len(augmented_texts), #yeni eklenen yorum yapan kısmına augmented etiketi yazılxcak
    "Yorum": augmented_texts
})


new_df = pd.concat([df, aug_df], ignore_index=True) #birleştirmr


new_df.to_csv("dataset_augmented.csv", index=False, encoding="utf-8-sig")

print("Augmentation tamamlandı dosya 'dataset_augmented.csv' olarak kaydedildi")
print(f"Temel nötr cümle sayısı: {len(neutral_texts)}")
print(f"Augmented nötr cümle sayısı: {len(augmented_texts)}")

#augmented verileri temizledim.
nltk.download('stopwords')

turkish_stopwords = set(stopwords.words('turkish'))

def clean_text(text):
    if pd.isnull(text):
        return ""

    text = text.lower()
    text = re.sub(r'[^\w\sçğıöşü]', ' ', text)
    text = re.sub(r'\d+', '', text)
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = ' '.join([word for word in text.split() if word not in turkish_stopwords])

    text = re.sub(r'\s+', ' ', text).strip()

    return text

df = pd.read_csv("/content/dataset_augmented.csv")

df["Temiz_Yorum"] = df["Yorum"].apply(clean_text)

df.to_csv("augmented500.csv", index=False)

print("✅ Temizlenmiş yorumlar 'augmented500' dosyasına kaydedildi!")

#AUGMENTED veri için sınıflandırma sonucu


df = pd.read_csv("/content/augmented500.csv")

df = df[['Yorum', 'Duygu']]


X_train, X_test, y_train, y_test = train_test_split(
    df['Yorum'], df['Duygu'], test_size=0.2, random_state=42
)

vectorizer = TfidfVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_vec, y_train)

y_pred = model.predict(X_test_vec)

print("Sınıflandırma Raporu:\n")
print(classification_report(y_test, y_pred, target_names=["Negatif", "Notr", "Pozitif"]))

print("Karmaşıklık Matrisi:\n")
print(confusion_matrix(y_test, y_pred))

df = pd.read_csv("/content/veriler_temiz.csv")

# pozitif negatif sözlük
pozitif_kelimeler = [
    "harika", "mükemmel", "razı olsun", "teşekkürler", "sağlık", "beğendim", "teşekkür", "sayenizde", "mutlu", "sevdim","helal olsun","bravo"
]
negatif_kelimeler = [
    "yazık", "berbat", "rezalet", "iğrenç", "kapatıl", "rüşvet", "iftira", "fena", "çürüme", "kapatılmalı", "istifa", "bıyık","soruşturma","yeter","suç"
]


def kelime_bazli_duygu(yorum):
    pozitif_sayi = sum(1 for kelime in pozitif_kelimeler if kelime in yorum)
    negatif_sayi = sum(1 for kelime in negatif_kelimeler if kelime in yorum)

    if pozitif_sayi > negatif_sayi:
        return "Pozitif"
    elif negatif_sayi > pozitif_sayi:
        return "Negatif"
    else:
        return "Nötr"

#her yorum icin fonksiyonu cagır
df["Tahmin"] = df["Temiz_Yorum"].apply(kelime_bazli_duygu)


print("Kelime bazlı duygu analizi dağılımı:")
print(df["Tahmin"].value_counts())


plt.figure(figsize=(3,3))
df["Tahmin"].value_counts().plot.pie(autopct="%1.1f%%", colors=sns.color_palette("Set2"))
plt.title("Kelime Bazlı Duygu Analizi Dağılımı")
plt.ylabel("")
plt.show()


print("\nÖrnek tahminler:")
print(df[["Temiz_Yorum", "Tahmin"]].head(15))

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report, accuracy_score
results = []
df = pd.read_csv("/content/veriler_temiz.csv")
print(df.head())


X = df["Yorum"]
y = df["Duygu"]   # 1Negatif 2Nötr 3Pozitif


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

vectorizer = TfidfVectorizer(max_features=5000)
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

models = {
    "Naive Bayes": MultinomialNB(),
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "SVM": LinearSVC()
}

for name, model in models.items():
    print(f"\n🤖 {name} 🤖")
    model.fit(X_train_tfidf, y_train)
    y_pred = model.predict(X_test_tfidf)

    acc = accuracy_score(y_test, y_pred)
    print("Accuracy:", acc)
    print(classification_report(y_test, y_pred, digits=2))

    report = classification_report(y_test, y_pred, output_dict=True)
    results.append({
        "Model": name,
        "Accuracy": acc,
        "F1_Negatif": report["1"]["f1-score"],
        "F1_Nötr": report["2"]["f1-score"],
        "F1_Pozitif": report["3"]["f1-score"],
    })


results_df = pd.DataFrame(results)
print("\nSonuç Tablosu:")
print(results_df)
#acc görselleştrme
plt.figure(figsize=(4,3))
sns.barplot(x="Model", y="Accuracy", data=results_df)
plt.title("Model Accuracy Karşılaştırması")
plt.ylim(0,1)
plt.show()

#f1 sonucu görselleşirme
f1_df = results_df.melt(id_vars="Model",
                        value_vars=["F1_Negatif", "F1_Nötr", "F1_Pozitif"],
                        var_name="Class", value_name="F1-Score")

plt.figure(figsize=(5,3))
sns.barplot(x="Model", y="F1-Score", hue="Class", data=f1_df)
plt.title("Her Model için F1 Skorları")
plt.ylim(0,1)
plt.legend(title="Sınıf")
plt.show()

!pip install catboost

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, confusion_matrix
from catboost import CatBoostClassifier

# 1. Veriyi oku
df = pd.read_csv("/content/veriler_temiz.csv")

# 2. Gerekli sütunları al
df = df[['Temiz_Yorum', 'Duygu']]
X = df['Temiz_Yorum']
y = df['Duygu']

# 3. Eğitim / test böl
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 4. TF-IDF vektörleştirme
vectorizer = TfidfVectorizer(max_features=5000)
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# 5. CatBoost modelini tanımla
model = CatBoostClassifier(
    iterations=500,        # ağaç sayısı
    learning_rate=0.1,     # öğrenme hızı
    depth=6,               # ağaç derinliği
    loss_function='MultiClass',
    eval_metric='TotalF1',
    verbose=100,           # her 100 iterasyonda çıktı ver
    random_seed=42
)

# 6. Modeli eğit
model.fit(X_train_vec, y_train, eval_set=(X_test_vec, y_test))

# 7. Tahmin
y_pred = model.predict(X_test_vec)

# 8. Rapor
print("\nSınıflandırma Raporu:\n")
print(classification_report(y_test, y_pred, target_names=["Negatif", "Notr", "Pozitif"]))

print("\nKarmaşıklık Matrisi:\n")
print(confusion_matrix(y_test, y_pred))

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

# 1. Veriyi oku
df = pd.read_csv("/content/veriler_temiz.csv")

# 2. Gerekli sütunları al
df = df[['Temiz_Yorum', 'Duygu']]
X = df['Temiz_Yorum']
y = df['Duygu']

# 3. Eğitim / test böl
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 4. TF-IDF vektörleştirme
vectorizer = TfidfVectorizer(max_features=5000)
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# 5. AdaBoost modelini tanımla
# Zayıf öğrenici olarak küçük derinlikli karar ağacı kullanıyoruz
base_estimator = DecisionTreeClassifier(max_depth=1, random_state=42)

model = AdaBoostClassifier(
    estimator=base_estimator,
    n_estimators=400,       # ağaç sayısı
    learning_rate=0.9,      # öğrenme hızı
    random_state=42
)

# 6. Modeli eğit
model.fit(X_train_vec.toarray(), y_train)  # AdaBoost sparse desteklemez → array'e çevirdik

# 7. Tahmin
y_pred = model.predict(X_test_vec.toarray())

# 8. Rapor
print("\nSınıflandırma Raporu:\n")
print(classification_report(y_test, y_pred, target_names=["Negatif", "Notr", "Pozitif"]))

print("\nKarmaşıklık Matrisi:\n")
print(confusion_matrix(y_test, y_pred))

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, confusion_matrix
from lightgbm import LGBMClassifier

# 1. Veriyi oku
df = pd.read_csv("/content/veriler_temiz.csv")

# 2. Sadece gerekli sütunları al
df = df[['Temiz_Yorum', 'Duygu']]
X = df['Temiz_Yorum']
y = df['Duygu']

# 3. Eğitim / test böl
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 4. TF-IDF vektörleştirme
vectorizer = TfidfVectorizer(max_features=5000)
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# 5. LightGBM classifier
model = LGBMClassifier(
    objective='multiclass',
    num_class=len(y.unique()),
    learning_rate=0.1,
    n_estimators=200,
    random_state=42,
    verbose=-1
)

# 6. Modeli eğit
model.fit(X_train_vec, y_train,
          eval_set=[(X_test_vec, y_test)],
          eval_metric='multi_logloss',
          )

# 7. Tahmin
y_pred = model.predict(X_test_vec)

# 8. Rapor
print("\nSınıflandırma Raporu:\n")
print(classification_report(y_test, y_pred, target_names=["Negatif", "Notr", "Pozitif"]))

print("\nKarmaşıklık Matrisi:\n")
print(confusion_matrix(y_test, y_pred))

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

# 1. Veriyi oku
df = pd.read_csv("/content/veriler_temiz.csv")

# 2. Gerekli sütunları al
df = df[['Temiz_Yorum', 'Duygu']]
X = df['Temiz_Yorum']
y = df['Duygu']

# 3. Eğitim / test böl
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 4. TF-IDF vektörleştirme
vectorizer = TfidfVectorizer(max_features=5000)
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# 5. Random Forest classifier
model = RandomForestClassifier(
    n_estimators=300,   # ağaç sayısı
    max_depth=None,     # sınırsız derinlik
    random_state=42,
    n_jobs=-1           # paralel çalıştır
)

# 6. Modeli eğit
model.fit(X_train_vec, y_train)

# 7. Tahmin
y_pred = model.predict(X_test_vec)

# 8. Rapor
print("\nSınıflandırma Raporu:\n")
print(classification_report(y_test, y_pred, target_names=["Negatif", "Notr", "Pozitif"]))

print("\nKarmaşıklık Matrisi:\n")
print(confusion_matrix(y_test, y_pred))

!pip install

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout

# 1. Veriyi oku
df = pd.read_csv("/content/veriler_temiz.csv")

# 2. Gerekli sütunları al
df = df[['Temiz_Yorum', 'Duygu']]
X = df['Temiz_Yorum']
y = df['Duygu']

# 3. Label encoding (çünkü ANN one-hot veya integer ister)
encoder = LabelEncoder()
y = encoder.fit_transform(y)   # Negatif=0, Notr=1, Pozitif=2 gibi

# 4. Eğitim / test böl
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 5. TF-IDF vektörleştirme
vectorizer = TfidfVectorizer(max_features=5000)
X_train_vec = vectorizer.fit_transform(X_train).toarray()
X_test_vec = vectorizer.transform(X_test).toarray()

# 6. ANN modeli
model = Sequential([
    Dense(256, activation='relu', input_shape=(X_train_vec.shape[1],)),
    Dropout(0.3),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(3, activation='softmax')  # 3 sınıf için çıkış
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# 7. Eğit
history = model.fit(
    X_train_vec, y_train,
    epochs=30,
    batch_size=10,
    validation_data=(X_test_vec, y_test),
    verbose=1
)

# 8. Tahmin
y_pred_probs = model.predict(X_test_vec)
y_pred = y_pred_probs.argmax(axis=1)

# 9. Rapor
print("\nSınıflandırma Raporu:\n")
print(classification_report(y_test, y_pred, target_names=["Negatif", "Notr", "Pozitif"]))

print("\nKarmaşıklık Matrisi:\n")
print(confusion_matrix(y_test, y_pred))

